name: cipher_vault
description: "Widget that displays the secret Depending on the argument, is it a secret? displays either an animation or a secret"
version: 1.0.0
repository: https://github.com/MixKage/cipher_vault
homepage: https://github.com/MixKage/cipher_vault
issue_tracker: https://github.com/MixKage/cipher_vault/issues
topics: ["cipher_vault", "secrets", "passwords", "widgets"]


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
